@verbatim
                return {

                    // App shell
                    breadcrumbItems,
                    appLoading,
                    calendarEventsData,
                    tabDataLoaded,
                    loadTabData,
                    keepBarangLoaded,
                    namaStockLoaded,
                    budgetConfigLoaded,
                    bonusConfigLoaded,
                    isSidebarOpen,
                    kontenOpen,
                    analisaKontenOpen,
                    csOpen,
                    settingsGroupOpen,
                    performaOpen,
                    marketingOpen,
                    toggleMenuGroup,
                    submitting,
                    runtimeError,
                    notification,
                    confirmModal,
                    toggleSidebar,
                    closeSidebar,
                    refreshDashboard,

                    // Auth & user
                    currentUser,
                    isTeknisi,
                    loginForm,
                    handleLogin,
                    logout,
                    profileMenuOpen,
                    openProfileSetting,
                    saveProfileInfo,
                    saveProfileSetting,
                    loadAuthUsers,
                    loadActivityLogs,
                    submitAuthUserForm,
                    profileForm,
                    authUsers,
                    authUsersLoaded,
                    activityLogs,
                    activityLogsLoaded,
                    activityLogFilters,
                    authUserForm,
                    submittingInfo,
                    submittingPin,
                    submittingAuthUser,

                    // Navigation
                    activeTab,
                    switchTab,

                    // Utilities
                    formatNumber,
                    formatWaNumber,
                    formatCurrency,
                    formatShortDate,
                    formatFullDate,
                    getStatusColor,
                    calcAdminPct,
                    last12Months,
                    availableYears,
                    formatMonthLabel,
                    getStaggerStyle,

                    // Date range calendar picker
                    calendarOpen,
                    calendarDayModalOpen,
                    calendarDayModalDate,
                    calendarDayModalItems,
                    openCalendarDayModal,
                    resetCalendar,
                    calendarMode,
                    currentDateView,
                    monthNames,
                    keepBarangStatusOptions,
                    optionLabel,
                    monthOptionLabel,
                    openCalendar,
                    calendarTargetDate,
                    calendarDaysInMonth,
                    calendarEmptyDays,
                    selectDate,
                    changeMonth,
                    isSelectedDate,
                    isStartDate,
                    isEndDate,
                    isInRange,
                    isToday,
                    hoveredDate,
                    getDefaultDateRange,
                    saveFilterRange,
                    getFilterRef,

                    // Search select
                    searchSelectOpen,
                    searchSelectQuery,
                    toggleSearchSelect,
                    popoverStyle,
                    filteredFormatOptions,
                    filteredEditorOptions,
                    filteredTalentOptions,
                    filteredPlatformOptions,
                    filteredColabOptions,
                    toggleColab,
                    selectFormat,
                    selectStatus,
                    selectEditor,
                    toggleTalent,

                    // Shared options
                    formatOptions,
                    statusOptions,
                    editorOptions,
                    platformOptions,
                    getPlatformIcon,
                    togglePlatform,
                    hasAnyLink,
                    hasAnyMasterLink,
                    orderanEcommerceOptions,
                    orderanPengirimanOptions,
                    orderanStatusOptions,
                    unboxingStatusOptions,
                    orderanHandleOptions,
                    unitKategoriOptions,
                    unitBrandOptions,
                    nsSeriOptions,
                    namaStockKategoriOptions,
                    namaStockBrandOptions,
                    namaStockSeriOptions,
                    unitKondisiOptions,
                    unitAvailableOptions,
                    unitRAMOptions,
                    unitInternalOptions,
                    unitSizeOptions,
                    sharedUnitTypeOptions,
                    keepBarangTypeHpOptions,
                    getSeriOptions,
                    getBrandOptions,
                    getKategoriOptions,
                    claimLokasiOptions,
                    claimStatusOptions,
                    claimGaransiOptions,
                    claimSeriOptions,
                    keepBarangHandleByOptions,
                    keepBarangKasirByOptions,
                    keepBarangTeamGudangOptions,

                    // Master plan
                    masterPlanData,
                    masterSearch,
                    masterFilterRange,
                    masterForm,
                    modalOpen,
                    modalType,
                    contentTableSearch,
                    commonDateFilter,
                    insightDateFilter,

                    // Meta IG Analytics
                    metaStoryData,
                    metaFeedData,
                    metaStoryLoaded,
                    metaFeedLoaded,
                    metaUploading,
                    metaStorySearch,
                    metaFeedSearch,
                    metaFeedAccount,
                    metaFeedAccounts,
                    metaStoryDateFilter,
                    metaFeedDateFilter,
                    filteredMetaStory,
                    filteredMetaFeed,
                    metaStorySummary,
                    metaFeedSummary,
                    metaStoryInsights,
                    metaFeedInsights,
                    metaStoryPage,
                    metaStoryTotalPages,
                    pagedMetaStory,
                    metaStoryMonthlySummary,
                    metaFeedMonthlySummary,
                    metaFeedAccountLeaderboard,
                    metaStoryTop,
                    metaFeedTop,
                    handleMetaFileInput,
                    importMetaFolder,
                    metaShortDesc,
                    loadMetaStory,
                    loadMetaFeed,
                    filteredMasterPlanData,
                    masterPage,
                    masterTotalPages,
                    pagedMasterPlanData,
                    openCreateModal,
                    openEditModal,
                    saveMasterPlan,
                    deleteMasterPlan,
                    exportExcel,
                    exportPdf,

                    // Ideation
                    ideationViewMode,
                    ideationBoardMobileTab,
                    ideationDraftLabel,
                    isMobileViewport,
                    kanbanBuckets,
                    getKanbanItems,
                    getIdeaAgeLabel,
                    getIdeationTypeTone,
                    boardPages,
                    pagedKanbanBuckets,

                    // Distribution
                    distributionData,
                    distModalOpen,
                    distributionForm,
                    openDistModal,
                    saveDistribution,
                    deleteDistribution,
                    filteredDistributionData,
                    distributionPage,
                    distributionTotalPages,
                    pagedDistributionData,

                    // Analytics
                    analyticsData,
                    analyticsModalOpen,
                    analyticsForm,
                    openAnalyticsModal,
                    saveAnalytics,
                    deleteAnalytics,
                    filteredAnalyticsData,
                    analyticsPage,
                    analyticsTotalPages,
                    pagedAnalyticsData,
                    calculateScore,
                    getVelocity,
                    exportAnalyticsToPDF,
                    topContentByPlatform,
                    topContentCombined,
                    lowContentByPlatform,
                    lowContentCombined,

                    // Insight & Tren
                    analisaInsightTab,
                    colabVsNonColabStats,
                    contentFunnelStats,
                    monthlyTrendData,
                    productDemandStats,
                    orderOnlineSummary,
                    claimGaransiStats,

                    // Story schedule
                    storyData,
                    storyTab,
                    filteredStories,
                    storyModalOpen,
                    storyModalType,
                    storyForm,
                    storyPage,
                    storyTotalPages,
                    pagedStories,
                    loadStoryData,
                    openCreateStoryModal,
                    openEditStoryModal,
                    saveStory,
                    deleteStory,

                    // Unboxing
                    unboxingData,
                    unboxingSearch,
                    unboxingModalOpen,
                    unboxingModalType,
                    unboxingForm,
                    openUnboxingModal,
                    filteredUnboxingData,
                    unboxingPage,
                    unboxingTotalPages,
                    pagedUnboxingData,
                    saveUnboxing,
                    deleteUnboxing,
                    loadUnboxingData,

                    // Orderan online
                    orderanOnlineData,
                    orderanOnlineSearch,
                    orderanOnlineDateRange,
                    orderanOnlineModalOpen,
                    orderanOnlineForm,
                    openOrderanOnlineModal,
                    filteredOrderanOnlineData,
                    orderanPage,
                    orderanTotalPages,
                    pagedOrderanOnlineData,
                    saveOrderanOnline,
                    deleteOrderanOnline,
                    loadOrderanOnlineData,

                    // Unit ditanya
                    unitDitanyaData,
                    unitDitanyaSearch,
                    unitDitanyaDateRange,
                    unitDitanyaAvailableFilter,
                    unitDitanyaSortBy,
                    unitDitanyaSortDesc,
                    unitDitanyaModalOpen,
                    unitDitanyaForm,
                    openUnitDitanyaModal,
                    filteredUnitDitanyaData,
                    unitDitanyaPage,
                    unitDitanyaTotalPages,
                    pagedUnitDitanyaData,
                    saveUnitDitanya,
                    deleteUnitDitanya,
                    exportUnitDitanyaToPDF,
                    exportUnitDitanyaToExcel,
                    loadUnitDitanyaData,

                    // Claim garansi
                    claimGaransiData,
                    claimGaransiSearch,
                    claimGaransiLokasiFilter,
                    claimGaransiStatusFilter,
                    claimGaransiGaransiFilter,
                    claimGaransiModalOpen,
                    claimGaransiForm,
                    openClaimGaransiModal,
                    filteredClaimGaransiData,
                    claimPage,
                    claimTotalPages,
                    pagedClaimGaransiData,
                    saveClaimGaransi,
                    deleteClaimGaransi,
                    exportClaimGaransiToPDF,
                    exportClaimGaransiToExcel,
                    loadClaimGaransiData,

                    // Keep barang
                    keepBarangData,
                    keepBarangSearch,
                    keepBarangStatusFilter,
                    keepBarangHandleByFilter,
                    keepBarangModalOpen,
                    keepBarangModalType,
                    keepBarangForm,
                    keepBarangPage,
                    keepBarangTotalPages,
                    keepBarangSummary,
                    keepBarangUniqueStatus,
                    keepBarangUniqueHandleBy,
                    filteredKeepBarangData,
                    pagedKeepBarangData,
                    openKeepBarangModal,
                    saveKeepBarang,
                    deleteKeepBarang,
                    loadKeepBarangData,
                    keepBarangStatusClass,
                    keepBarangSisaHariClass,
                    exportKeepBarangToExcel,
                    exportKeepBarangToPDF,

                    // CS calendar
                    calendarFormContext,
                    csModalType,
                    calendarActiveDate,
                    changeCalendarMonth,
                    getCalendarDaysInMonth,
                    getCalendarEmptyDays,
                    isTodayCalendar,
                    getCalendarItems,
                    calendarMonthIsEmpty,

                    // Summary cards per menu
                    masterSummary,
                    ideationSummary,
                    distributionSummary,
                    analyticsSummary,
                    unboxingSummary,
                    storySummary,
                    promoSummary,
                    orderanSummary,
                    unitDitanyaSummary,
                    claimSummary,
                    hargaSummary,
                    lpjkSummary,

                    // Settings
                    settings,
                    settingsDraft,
                    settingsDirty,
                    activeSettingTab,
                    savingSettings,
                    settingsMenuGroups,
                    settingsSearchQuery,
                    settingsFilterMode,
                    settingsFilterOptions,
                    filteredSettingsMenuGroups,
                    filteredSettingsTabCount,
                    settingsDirtyTabCount,
                    settingsDirtyValueCount,
                    activeSettingValueSearch,
                    settingsDetailModalOpen,
                    showSettingsBulkAdd,
                    settingsBulkAddText,
                    filteredActiveSettingEntries,
                    activeSettingObjectSections,
                    getSettingTabLabel,
                    getSettingTabCount,
                    getSettingFilledCount,
                    getSettingEmptyCount,
                    isSettingTabDirty,
                    isSettingTabObject,
                    markSettingsDirty,
                    resetSettingsDraft,
                    setActiveSettingTab,
                    closeSettingsDetailModal,
                    updateSettingOption,
                    addSettingOption,
                    sortSettingOptions,
                    clearEmptySettingOptions,
                    toggleSettingsBulkAdd,
                    applySettingsBulkAdd,
                    askSettingAction,
                    saveSettingsBackend,

                    // Nama stock
                    namaStockRows,
                    namaStockSearchQuery,
                    namaStockKategoriFilter,
                    namaStockBrandFilter,
                    namaStockSaving,
                    showNamaStockFormModal,
                    namaStockFormMode,
                    namaStockForm,
                    namaStockFilteredRows,
                    namaStockFilterKategoriOptions,
                    namaStockFilterBrandOptions,
                    namaStockPage,
                    namaStockTotalPages,
                    pagedNamaStockRows,
                    openNamaStockFormModal,
                    closeNamaStockFormModal,
                    submitNamaStockForm,
                    removeNamaStockRow,
                    saveNamaStockSettings,

                    // Bonus report
                    bonusConfig,
                    bonusFilter,
                    bonusMonth, bonusYear,
                    showBonusSettings,
                    bonusPage,
                    bonusTotalPages,
                    pagedBonusRows,
                    filteredBonusRows,
                    bonusTotal,
                    talentPage,
                    talentTotalPages,
                    pagedTalentRows,
                    talentBonusRows,
                    talentDashboardData,
                    saveBonusConfig,
                    exportBonusToPDF,
                    exportBonusToExcel,

                    // Editor performance
                    editorMonth, editorYear, editorDateRange,
                    editorDashboardData,
                    editorPage,
                    editorTotalPages,
                    pagedEditorRows,

                    // Program promo
                    promoData,
                    promoSearch,
                    promoPage,
                    promoModalOpen,
                    promoModalType,
                    promoForm,
                    promoPeriodePreset,
                    promoTempDate,
                    kategoriPromoOptions,
                    filteredPromoData,
                    groupedPromoRows,
                    promoTotalPages,
                    pagedPromoRows,
                    loadPromoData,
                    openPromoModal,
                    savePromo,
                    deletePromo,
                    exportPromoToPDF,
                    applyPromoPeriodePreset,
                    syncPromoPerideText,
                    // Sell out
                    sellOutData,
                    sellOutSearch,
                    sellOutVendorFilter,
                    sellOutMonth,
                    sellOutPage,
                    sellOutModalOpen,
                    sellOutModalType,
                    sellOutForm,
                    sellOutVendorOptions,
                    filteredSellOutData,
                    sellOutSummary,
                    sellOutTotalPages,
                    pagedSellOutData,
                    getSellOutProgress,
                    loadSellOutData,
                    buildSellOutProductName,
                    openSellOutModal,
                    saveSellOut,
                    deleteSellOut,
                    exportSellOutToExcel,
                    exportSellOutToPDF,

                    // Ads log
                    adsData,
                    adsSearch,
                    adsDateFilter,
                    adsPage,
                    adsModalOpen,
                    adsModalType,
                    adsForm,
                    adsPlatformOptions,
                    adsKategoriOptions,
                    filteredAdsData,
                    adsTotalPages,
                    pagedAdsData,
                    adsComputedScore,
                    adsSaldoPlatform,
                    adsPlatformColor,
                    openAdsModal,
                    saveAdsRow,
                    deleteAdsRow,
                    exportAdsLogToPDF,

                    // Harga & Kompetitor
                    hargaKompetitorData,
                    hargaKompetitorSearch,
                    hargaKompetitorDateFilter,
                    hargaKompetitorPage,
                    hargaKompetitorModalOpen,
                    hargaKompetitorModalType,
                    hargaKompetitorForm,
                    filteredHargaKompetitorData,
                    hargaKompetitorTotalPages,
                    pagedHargaKompetitorData,
                    openHargaKompetitorModal,
                    saveHargaKompetitor,
                    deleteHargaKompetitor,
                    exportPriceComparisonToPDF,

                    // Laporan Event (LPJK)
                    lpjkData,
                    lpjkSearch,
                    lpjkPage,
                    lpjkModalOpen,
                    lpjkModalType,
                    lpjkForm,
                    lpjkStatusOptions,
                    lpjkDetailModalOpen,
                    activeLpjkRow,
                    lpjkDetailData,
                    lpjkDetailItem,
                    lpjkExpenseCategories,
                    lpjkDetailGrouped,
                    lpjkDetailTotal,
                    filteredLpjkData,
                    lpjkTotalPages,
                    pagedLpjkData,
                    openLpjkModal,
                    saveLpjk,
                    deleteLpjk,
                    openLpjkDetail,
                    closeLpjkDetail,
                    saveLpjkDetail,
                    deleteLpjkDetail,
                    exportLpjkDetailToPDF,

                    // Asset Vendor Inventory
                    aviData,
                    aviSearch,
                    aviPage,
                    aviModalOpen,
                    aviModalType,
                    aviForm,
                    aviConditionOptions,
                    filteredAviData,
                    aviTotalPages,
                    pagedAviData,
                    aviUniqueVendors,
                    aviUniqueBrands,
                    aviTotalQuantity,
                    aviSummaryChips,
                    openAviModal,
                    saveAvi,
                    deleteAvi,

                    // Budgeting
                    budgetConfig,
                    budgetDateFilter,
                    showBudgetSettings,
                    showColabListModal,
                    budgetCalculations,
                    budgetSummary,
                    saveBudgetServer,
                    loadBudgetingConfig,
                    exportBudgetToPDF,
                    exportBudgetToExcel,
                };
            },

@endverbatim
